#!/usr/bin/env python3
"""
Builds the Solitaire mark: a white capital S on black.

Same convention as the rest of the gi-os Light collection, where LightFog's
scripts/generate-icon.js draws the first letter of the app name in Public Sans
on a black square. That one only needs a PNG because LightFog is a plain Android
app with a launcher icon. LightOS tools have no launcher icon, so this also emits
an Android vector drawable that overrides the SDK's splash mark.

    python3 tools/generate_icon.py path/to/PublicSans-Regular.ttf

Writes:
    assets/icon.png                                    1024 square, for the repo
    tool/src/main/res/drawable/loading_text_icon.xml    the splash mark
"""

import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Identity
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

LETTER = "S"

# Matches LightFog: an 85.4pt letter on a 100pt square.
PNG_SIZE = 1024
PNG_FONT_RATIO = 85.4 / 100

# The SDK's own splash drawable is a 240 square, so this one has to be too.
VECTOR_SIZE = 240
# Height of the letter as a fraction of the drawable. 85.4pt of Public Sans has a
# cap height near 62pt, so the same proportion holds here.
VECTOR_LETTER_RATIO = 0.62

REPO = Path(__file__).resolve().parent.parent


def write_png(font_path: Path) -> Path:
    image = Image.new("L", (PNG_SIZE, PNG_SIZE), 0)
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(str(font_path), int(PNG_SIZE * PNG_FONT_RATIO))

    # Centre on the ink, not on the line box, so the letter sits optically true.
    left, top, right, bottom = draw.textbbox((0, 0), LETTER, font=font)
    x = (PNG_SIZE - (right - left)) / 2 - left
    y = (PNG_SIZE - (bottom - top)) / 2 - top
    draw.text((x, y), LETTER, fill=255, font=font)

    out = REPO / "assets" / "icon.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    image.convert("RGB").save(out, optimize=True)
    return out


def write_vector(font_path: Path) -> Path:
    font = TTFont(str(font_path))
    glyph_set = font.getGlyphSet()
    glyph_name = font.getBestCmap()[ord(LETTER)]
    glyph = glyph_set[glyph_name]

    # Measure the outline before drawing it, so it can be scaled to fit.
    bounds_pen = SVGPathPen(glyph_set)
    glyph.draw(bounds_pen)
    from fontTools.pens.boundsPen import BoundsPen

    bounds = BoundsPen(glyph_set)
    glyph.draw(bounds)
    x_min, y_min, x_max, y_max = bounds.bounds

    scale = (VECTOR_SIZE * VECTOR_LETTER_RATIO) / (y_max - y_min)
    # Flip the y axis: fonts measure up from the baseline, drawables measure down.
    transform = (
        Identity.translate(
            (VECTOR_SIZE - (x_max - x_min) * scale) / 2 - x_min * scale,
            (VECTOR_SIZE + (y_max - y_min) * scale) / 2 + y_min * scale,
        )
        .scale(scale, -scale)
    )

    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.2f}")
    glyph.draw(TransformPen(pen, transform))
    path_data = pen.getCommands()

    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
    Overrides the drawable of the same name in sdk:client, which is the SDK's
    "loading..." splash mark. Resources in the application module take
    precedence over resources from a library module, so this needs no manifest
    change: LightOS tools have no launcher icon, and the splash is the one place
    a tool can show a mark of its own.

    Generated by tools/generate_icon.py. Public Sans, the same letterform the
    rest of the gi-os Light collection uses.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{VECTOR_SIZE}dp"
    android:height="{VECTOR_SIZE}dp"
    android:viewportWidth="{VECTOR_SIZE}"
    android:viewportHeight="{VECTOR_SIZE}">
  <path
      android:pathData="{path_data}"
      android:fillColor="#fff"
      android:fillType="nonZero"/>
</vector>
"""
    out = REPO / "tool" / "src" / "main" / "res" / "drawable" / "loading_text_icon.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(xml)
    return out


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    font_path = Path(sys.argv[1])
    if not font_path.is_file():
        sys.exit(f"no font at {font_path}")
    for path in (write_png(font_path), write_vector(font_path)):
        print(f"wrote {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
