#!/usr/bin/env python3
"""
Builds the Solitaire mark: a white capital S on black.

Same convention as the rest of the gi-os Light collection, where LightFog's
scripts/generate-icon.js draws the first letter of the app name in Public Sans
on a black square. That one only needs a PNG because LightFog is a plain Android
app with a launcher icon. LightOS tools have no launcher icon, so this also emits
an Android vector drawable that overrides the SDK's splash mark.

    python3 tools/generate_icon.py path/to/PublicSans-Regular.ttf

Writes:
    assets/icon.png                                       1024 square, for the repo
    tool/src/main/res/drawable/loading_text_icon.xml       the splash mark
    tool/src/main/res/drawable/ic_launcher_foreground.xml  launcher icon, letter
    tool/src/main/res/drawable/ic_launcher_background.xml  launcher icon, black
    tool/src/main/res/mipmap-anydpi-v26/ic_launcher.xml    the adaptive icon
"""

import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Identity
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

LETTER = "S"

# Matches LightFog: an 85.4pt letter on a 100pt square.
PNG_SIZE = 1024
PNG_FONT_RATIO = 85.4 / 100

# The SDK's own splash drawable is a 240 square, so this one has to be too.
VECTOR_SIZE = 240
# Height of the letter as a fraction of the drawable. 85.4pt of Public Sans has a
# cap height near 62pt, so the same proportion holds here.
VECTOR_LETTER_RATIO = 0.62

# An adaptive icon is always a 108 square, of which the middle 72 is the part
# guaranteed to survive whatever mask the launcher applies. Keeping the letter at
# the same 0.62 of that visible square puts it at 0.62 * 72 / 108 of the whole.
LAUNCHER_SIZE = 108
LAUNCHER_LETTER_RATIO = 0.62 * 72 / 108

# Legacy launcher icon sizes. Never masked, so these are full bleed like LightFog's.
LAUNCHER_DENSITIES = {
    "mdpi": 48,
    "hdpi": 72,
    "xhdpi": 96,
    "xxhdpi": 144,
    "xxxhdpi": 192,
}

REPO = Path(__file__).resolve().parent.parent


def raster(font_path: Path, size: int) -> Image.Image:
    """A white letter on a black square, [size] px across."""
    image = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(str(font_path), int(size * PNG_FONT_RATIO))

    # Centre on the ink, not on the line box, so the letter sits optically true.
    left, top, right, bottom = draw.textbbox((0, 0), LETTER, font=font)
    x = (size - (right - left)) / 2 - left
    y = (size - (bottom - top)) / 2 - top
    draw.text((x, y), LETTER, fill=255, font=font)
    return image.convert("RGB")


def write_png(font_path: Path) -> Path:
    out = REPO / "assets" / "icon.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    raster(font_path, PNG_SIZE).save(out, optimize=True)
    return out


def letter_path(font_path: Path, box: float, letter_ratio: float) -> str:
    """The letter as SVG path data, scaled to [letter_ratio] of a [box] square."""
    font = TTFont(str(font_path))
    glyph_set = font.getGlyphSet()
    glyph = glyph_set[font.getBestCmap()[ord(LETTER)]]

    bounds = BoundsPen(glyph_set)
    glyph.draw(bounds)
    x_min, y_min, x_max, y_max = bounds.bounds

    scale = (box * letter_ratio) / (y_max - y_min)
    # Flip the y axis: fonts measure up from the baseline, drawables measure down.
    transform = Identity.translate(
        (box - (x_max - x_min) * scale) / 2 - x_min * scale,
        (box + (y_max - y_min) * scale) / 2 + y_min * scale,
    ).scale(scale, -scale)

    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.2f}")
    glyph.draw(TransformPen(pen, transform))
    return pen.getCommands()


def write_launcher(font_path: Path) -> list[Path]:
    """
    The launcher icon, as an adaptive icon.

    minSdk is 34, so every device that can install this understands adaptive
    icons and no legacy density buckets are needed.
    """
    path_data = letter_path(font_path, LAUNCHER_SIZE, LAUNCHER_LETTER_RATIO)
    res = REPO / "tool" / "src" / "main" / "res"

    foreground = res / "drawable" / "ic_launcher_foreground.xml"
    foreground.parent.mkdir(parents=True, exist_ok=True)
    foreground.write_text(f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{LAUNCHER_SIZE}dp"
    android:height="{LAUNCHER_SIZE}dp"
    android:viewportWidth="{LAUNCHER_SIZE}"
    android:viewportHeight="{LAUNCHER_SIZE}">
  <path
      android:pathData="{path_data}"
      android:fillColor="#fff"
      android:fillType="nonZero"/>
</vector>
""")

    background = res / "drawable" / "ic_launcher_background.xml"
    background.write_text(f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{LAUNCHER_SIZE}dp"
    android:height="{LAUNCHER_SIZE}dp"
    android:viewportWidth="{LAUNCHER_SIZE}"
    android:viewportHeight="{LAUNCHER_SIZE}">
  <path
      android:pathData="M0,0h{LAUNCHER_SIZE}v{LAUNCHER_SIZE}h-{LAUNCHER_SIZE}z"
      android:fillColor="#000"/>
</vector>
""")

    adaptive = res / "mipmap-anydpi-v26" / "ic_launcher.xml"
    adaptive.parent.mkdir(parents=True, exist_ok=True)
    adaptive.write_text("""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_icon.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
""")

    written = [foreground, background, adaptive]

    # Raster copies as well, at the unqualified densities.
    #
    # Android itself never reads these: minSdk is 34, so the anydpi-v26 folder
    # always wins and the launcher gets the adaptive icon. They are here for
    # everything that reads an APK without applying resource qualifiers. Plenty of
    # tools do, and an icon that only exists as vector XML comes back blank in
    # those: they cannot rasterise it, so they find the reference and give up.
    # A few kilobytes buys an icon that shows up everywhere.
    for folder, size in LAUNCHER_DENSITIES.items():
        png = res / f"mipmap-{folder}" / "ic_launcher.png"
        png.parent.mkdir(parents=True, exist_ok=True)
        raster(font_path, size).save(png, optimize=True)
        written.append(png)

    return written


def write_vector(font_path: Path) -> Path:
    path_data = letter_path(font_path, VECTOR_SIZE, VECTOR_LETTER_RATIO)

    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
    Overrides the drawable of the same name in sdk:client, which is the SDK's
    "loading..." splash mark. Resources in the application module take
    precedence over resources from a library module, so this needs no manifest
    change: LightOS tools have no launcher icon, and the splash is the one place
    a tool can show a mark of its own.

    Generated by tools/generate_icon.py. Public Sans, the same letterform the
    rest of the gi-os Light collection uses.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{VECTOR_SIZE}dp"
    android:height="{VECTOR_SIZE}dp"
    android:viewportWidth="{VECTOR_SIZE}"
    android:viewportHeight="{VECTOR_SIZE}">
  <path
      android:pathData="{path_data}"
      android:fillColor="#fff"
      android:fillType="nonZero"/>
</vector>
"""
    out = REPO / "tool" / "src" / "main" / "res" / "drawable" / "loading_text_icon.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(xml)
    return out


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    font_path = Path(sys.argv[1])
    if not font_path.is_file():
        sys.exit(f"no font at {font_path}")
    written = [write_png(font_path), write_vector(font_path), *write_launcher(font_path)]
    for path in written:
        print(f"wrote {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
